//! Payload parity test against tinytuya.
//!
//! tinytuya is treated as the reference implementation. The fixture
//! `tests/fixtures/tinytuya_payloads.json` is generated by
//! `tests/fixtures/gen_tinytuya_payloads.py` (run it under the venv that has
//! tinytuya installed) and records, for every
//! (protocol version x device type x command x data) combination, the command
//! code and JSON payload tinytuya emits with the wall clock pinned.
//!
//! This test feeds the identical inputs to rustuya's `generate_payload` and
//! asserts the command code and (order-insensitive) JSON payload match. Cases
//! where rustuya *intentionally* differs from tinytuya are listed in
//! `KNOWN_DIVERGENCES` with a rationale; those are reported but do not fail the
//! build.

use rustuya::protocol::{CommandType, DeviceType, Version, get_protocol};
use serde_json::Value;
use std::str::FromStr;

const FIXTURE: &str = include_str!("fixtures/tinytuya_payloads.json");

fn version_from_str(s: &str) -> Version {
    match s {
        "3.1" => Version::V3_1,
        "3.2" => Version::V3_2,
        "3.3" => Version::V3_3,
        "3.4" => Version::V3_4,
        "3.5" => Version::V3_5,
        other => panic!("unknown version in fixture: {other}"),
    }
}

fn command_from_str(s: &str) -> CommandType {
    match s {
        "ApConfig" => CommandType::ApConfig,
        "Control" => CommandType::Control,
        "Status" => CommandType::Status,
        "HeartBeat" => CommandType::HeartBeat,
        "DpQuery" => CommandType::DpQuery,
        "ControlNew" => CommandType::ControlNew,
        "DpQueryNew" => CommandType::DpQueryNew,
        "UpdateDps" => CommandType::UpdateDps,
        "SceneExecute" => CommandType::SceneExecute,
        "ReqDevInfo" => CommandType::ReqDevInfo,
        "LanExtStream" => CommandType::LanExtStream,
        other => panic!("unknown command in fixture: {other}"),
    }
}

/// Returns `Some(reason)` when (version, dev_type, command) is a documented,
/// intentional divergence from tinytuya — reported but not fatal.
///
/// There are currently none: rustuya matches tinytuya for every generated case.
/// Add an arm here returning `Some(reason)` if a deliberate difference is ever
/// introduced, so it's documented rather than silently failing the test.
fn known_divergence(_version: &str, _dev_type: &str, _command: &str) -> Option<&'static str> {
    None
}

#[test]
fn tinytuya_payload_parity() {
    let root: Value = serde_json::from_str(FIXTURE).expect("fixture is valid JSON");
    let device_id = root["device_id"].as_str().expect("device_id");
    let cases = root["cases"].as_array().expect("cases array");

    let mut unexpected: Vec<String> = Vec::new();
    let mut allowed: Vec<String> = Vec::new();
    let mut checked = 0usize;

    for case in cases {
        let version_s = case["version"].as_str().unwrap();
        let dev_type_s = case["dev_type"].as_str().unwrap();
        let command_s = case["command"].as_str().unwrap();
        let data = &case["data"];
        let t = case["t"].as_u64().unwrap();
        let expected_cmd = case["expected_cmd"].as_u64().unwrap() as u32;
        let expected_payload = &case["expected_payload"];

        let version = version_from_str(version_s);
        let dev_type = DeviceType::from_str(dev_type_s).unwrap();
        let command = command_from_str(command_s);
        let data_opt = if data.is_null() {
            None
        } else {
            Some(data.clone())
        };

        let proto = get_protocol(version, dev_type);
        let (cmd, payload) = proto
            .generate_payload(device_id, command, data_opt, None, t)
            .expect("rustuya generate_payload");

        let cmd_ok = cmd == expected_cmd;
        let payload_ok = &payload == expected_payload;
        checked += 1;

        if cmd_ok && payload_ok {
            continue;
        }

        let detail = format!(
            "{version_s} {dev_type_s} {command_s} data={data}\n     tinytuya: cmd={expected_cmd} {expected_payload}\n     rustuya : cmd={cmd} {payload}"
        );

        match known_divergence(version_s, dev_type_s, command_s) {
            Some(reason) => allowed.push(format!("[{reason}] {detail}")),
            None => unexpected.push(detail),
        }
    }

    eprintln!("tinytuya parity: checked {checked} cases");
    if !allowed.is_empty() {
        eprintln!(
            "\n--- known/intentional divergences ({}) ---",
            allowed.len()
        );
        for d in &allowed {
            eprintln!("  {d}");
        }
    }
    if !unexpected.is_empty() {
        eprintln!("\n--- UNEXPECTED divergences ({}) ---", unexpected.len());
        for d in &unexpected {
            eprintln!("  {d}");
        }
        panic!(
            "{} unexpected payload divergence(s) from tinytuya (see above)",
            unexpected.len()
        );
    }
}
